version: '3.9'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686"  # Web UI
      - "14250:14250"  # OTLP gRPC (OTel Collector pushes here)

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.95.0
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"  # OTLP gRPC (Spring Boot sends traces here)
      - "4318:4318"  # OTLP HTTP
    depends_on:
      - jaeger
